# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: adder.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61\x64\x64\x65r.proto\x12\x03\x61pi\"\"\n\nAddRequest\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"\x1d\n\x0b\x41\x64\x64Response\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32\x33\n\x05\x41\x64\x64\x65r\x12*\n\x03\x41\x64\x64\x12\x0f.api.AddRequest\x1a\x10.api.AddResponse\"\x00\x42\x07Z\x05./apib\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'adder_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\005./api'
  _ADDREQUEST._serialized_start=20
  _ADDREQUEST._serialized_end=54
  _ADDRESPONSE._serialized_start=56
  _ADDRESPONSE._serialized_end=85
  _ADDER._serialized_start=87
  _ADDER._serialized_end=138
# @@protoc_insertion_point(module_scope)
